name = "BlochSpins"
uuid = "256207cc-4c09-4d5f-9b7b-1beb86bf7525"
version = "0.1.0"
authors = ["sota <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
BlochSpinsMakieExt = "Makie"

[compat]
Arpack = "0.5.4"
CairoMakie = "0.15.8"
LinearAlgebra = "1.12.0"
Makie = "0.24.8"
StaticArrays = "1.9.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Makie", "CairoMakie"]
