name = "BlochSpins"
uuid = "256207cc-4c09-4d5f-9b7b-1beb86bf7525"
version = "0.1.0"
authors = ["sota <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]